FORMAT: 1A
HOST: http://docs.sitecoreship.apiary.io/

# Sitecore.Ship

The package offers a simple API to help consumers install their packages into Sitecore over an internet connection.

## Sitecore.Ship API Root [/services]

Returns information on the currently installed Sitecore.Ship.

### Retrieve information on the installed Sitecore.Ship [GET]

+ Response 200 (application/json)

        {
            "sitecore.ship.version": "0.4.0" 
        }