FORMAT: 1A
HOST: http://docs.sitecoreship.apiary.io/

# Sitecore.Ship

Package is a simple API allowing consumers to install packages into a Sitecore instance.

# Sitecore.Ship API Root [/services]

Returns information on the currently installed Sitecore.Ship.

## Retrieve information on the installed Sitecore.Ship [GET]

+ Response 200 (application/json)

        {
            "sitecore.ship.version": "0.4.0" 
        }




